# Generated by Django 4.2.7 on 2023-11-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=10)),
                ('destination_city', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('adults_count', models.CharField(max_length=20)),
                ('children_count', models.CharField(max_length=20)),
                ('infants_count', models.CharField(max_length=20)),
            ],
        ),
    ]
